<?php

namespace App\Http\Controllers\Customer;

use App\Http\Controllers\Controller; // <-- CRITICAL: This was missing!
use App\Models\CustomerInfo\Company;
use Illuminate\Http\Request;
use Inertia\Inertia;

class CustomerInfoController extends Controller
{
    /**
     * Display a listing of companies with search, filters, and pagination.
     */
    public function index(Request $request)
    {
        // 1. Sanitize the pagination input (Fallback to 12 if missing or invalid)
        $perPage = $request->integer('per_page', 12);
        
        // Safety check: Cap maximum items per page to prevent backend memory issues
        if ($perPage < 1) {
            $perPage = 12;
        } elseif ($perPage > 100) {
            $perPage = 100; 
        }

        $companies = Company::query()
            // Search Query (checks Company Name, SAP Code, or Address)
            ->when($request->input('search'), function ($query, $search) {
                $query->where(function ($q) use ($search) {
                    $q->where('company_name', 'like', "%{$search}%")
                      ->orWhere('sap_code', 'like', "%{$search}%")
                      ->orWhere('address', 'like', "%{$search}%");
                });
            })
            // Dropdown Filter: Client Category
            ->when($request->input('category'), function ($query, $category) {
                $query->where('client_category', $category);
            })
            // Dropdown Filter: Client Type
            ->when($request->input('type'), function ($query, $type) {
                $query->where('client_type', $type);
            })
            // Dropdown Filter: Status (Active/Inactive)
            ->when($request->input('status'), function ($query, $status) {
                $query->where('status', $status);
            })
            // Default sorting by latest ID or request specifications
            ->orderBy($request->input('sort_by', 'id'), $request->input('sort_order', 'desc'))
            // 2. Use the dynamic perPage integer here
            ->paginate($perPage)
            // Appends current filters onto the pagination links generated by Laravel
            ->withQueryString();

        // Send data directly to your React View component
      return Inertia::render('CustomerManagement/CustomerInfo/Index', [
        'companies' => $companies,
        'filters'   => $request->only(['search', 'category', 'type', 'status', 'per_page']),
        ]);
    }

    /**
     * Display the specified company profile layout.
     */
    public function show($id)
    {
        $company = Company::findOrFail($id);

        return Inertia::render('Companies/Show', [
            'company' => $company,
        ]);
    }
}